name:any build test folder 01 use

on:
  push:
    branches: 
      - develop
#    paths:
#      - 'folder01/**'

  pull_request:
    branches: 
      - develop
#    path:
#      - 'folder01/**'

jobs:
  folder01-build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.301'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
